name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install eslint
        run: npm install eslint --save-dev
      - name: Install parsers and plugins
        run: npm install --save-dev @babel/eslint-parser eslint-plugin-react --legacy-peer-deps
      - name: Check style
        run: npm run eslint